kind: Pod
apiVersion: v1
metadata:
  name: postgres-master78
  namespace: svr-app
  labels:
    app: postgres
spec:
  nodeName: node78
  containers:
    - name: postgres
      image: postgres:13.0
      env:
        - name: POSTGRES_PASSWORD
          value: admin888
      args:
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"
      ports:
        - name: server
          containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: postgres-config
          mountPath: "/etc/postgresql"
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-config
      configMap:
        name: postgres
        items:
          - key: "master.conf"
            path: "postgresql.conf"
    - name: postgres-data
      hostPath:
        path: /data/k8s-pv/postgres
---
kind: Pod
apiVersion: v1
metadata:
  name: postgres-slave79
  namespace: svr-app
  labels:
    app: postgres
spec:
  nodeName: node79
  containers:
    - name: postgres
      image: postgres:13.0
      env:
        - name: POSTGRES_PASSWORD
          value: admin888
      args:
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"
      ports:
        - name: server
          containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: postgres-config
          mountPath: "/etc/postgresql"
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-config
      configMap:
        name: postgres
        items:
          - key: "slave.conf"
            path: "postgresql.conf"
          - key: "recovery.conf"
            path: "recovery.conf"
    - name: postgres-data
      hostPath:
        path: /data/k8s-pv/postgres
---
kind: Pod
apiVersion: v1
metadata:
  name: postgres-slave80
  namespace: svr-app
  labels:
    app: postgres
spec:
  nodeName: node80
  containers:
    - name: postgres
      image: postgres:13.0
      env:
        - name: POSTGRES_PASSWORD
          value: admin888
      args:
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"
      ports:
        - name: server
          containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: postgres-config
          mountPath: "/etc/postgresql"
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-config
      configMap:
        name: postgres
        items:
          - key: "slave.conf"
            path: "postgresql.conf"
          - key: "recovery.conf"
            path: "recovery.conf"
    - name: postgres-data
      hostPath:
        path: /data/k8s-pv/postgres
