apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: app-log
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.9.3
          volumeMounts:
          - name: filebeat
            mountPath: /usr/share/filebeat/filebeat.yml
          - name: filebeat-data
            mountPath: /usr/share/filebeat/data
          - name: filebeat-logs
            mountPath: /usr/share/filebeat/logs
          - name: k8s-pv
            mountPath: /data/k8s-pv
      volumes:
      - name: filebeat
        hostPath:
          path: /data/k8s-pv/filebeat/filebeat.yml
      - name: filebeat-data
        hostPath:
          path: /data/k8s-pv/filebeat/data
      - name: filebeat-logs
        hostPath:
          path: /data/k8s-pv/filebeat/logs
      - name: k8s-pv
        hostPath:
          path: /data/k8s-pv
