kind: Pod
apiVersion: v1
metadata:
  name: elasticsearch-node78
  namespace: svr-app
  labels:
    app: elasticsearch
spec:
  nodeName: node78
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      env:
        - name: node.name
          value: node-78
      ports:
        - name: client
          containerPort: 9200
          hostPort: 9200
        - name: server
          containerPort: 9300
          hostPort: 9300
      volumeMounts:
        - name: elasticsearch-config
          mountPath: "/usr/share/elasticsearch/config"
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-logs
          mountPath: /usr/share/elasticsearch/logs
  volumes:
    - name: elasticsearch-config
      configMap:
        name: elasticsearch
        items:
          - key: "elasticsearch.yml"
            path: "elasticsearch.yml"
          - key: "jvm.options"
            path: "jvm.options"
          - key: "log4j2.properties"
            path: "log4j2.properties"
    - name: elasticsearch-data
      hostPath:
        path: /data/k8s-pv/elasticsearch/data
    - name: elasticsearch-logs
      hostPath:
        path: /data/k8s-pv/elasticsearch/logs
---
kind: Pod
apiVersion: v1
metadata:
  name: elasticsearch-node79
  namespace: svr-app
  labels:
    app: elasticsearch
spec:
  nodeName: node79
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      env:
        - name: node.name
          value: node-79
      ports:
        - name: client
          containerPort: 9200
          hostPort: 9200
        - name: server
          containerPort: 9300
          hostPort: 9300
      volumeMounts:
        - name: elasticsearch-config
          mountPath: "/usr/share/elasticsearch/config"
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-logs
          mountPath: /usr/share/elasticsearch/logs
  volumes:
    - name: elasticsearch-config
      configMap:
        name: elasticsearch
        items:
          - key: "elasticsearch.yml"
            path: "elasticsearch.yml"
          - key: "jvm.options"
            path: "jvm.options"
          - key: "log4j2.properties"
            path: "log4j2.properties"
    - name: elasticsearch-data
      hostPath:
        path: /data/k8s-pv/elasticsearch/data
    - name: elasticsearch-logs
      hostPath:
        path: /data/k8s-pv/elasticsearch/logs
---
kind: Pod
apiVersion: v1
metadata:
  name: elasticsearch-node80
  namespace: svr-app
  labels:
    app: elasticsearch
spec:
  nodeName: node80
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
      env:
        - name: node.name
          value: node-80
      ports:
        - name: client
          containerPort: 9200
          hostPort: 9200
        - name: server
          containerPort: 9300
          hostPort: 9300
      volumeMounts:
        - name: elasticsearch-config
          mountPath: "/usr/share/elasticsearch/config"
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-logs
          mountPath: /usr/share/elasticsearch/logs
  volumes:
    - name: elasticsearch-config
      configMap:
        name: elasticsearch
        items:
          - key: "elasticsearch.yml"
            path: "elasticsearch.yml"
          - key: "jvm.options"
            path: "jvm.options"
          - key: "log4j2.properties"
            path: "log4j2.properties"
    - name: elasticsearch-data
      hostPath:
        path: /data/k8s-pv/elasticsearch/data
    - name: elasticsearch-logs
      hostPath:
        path: /data/k8s-pv/elasticsearch/logs
