kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: log-app
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.9.3
          volumeMounts:
          - name: logstash-pipeline
            mountPath: /usr/share/logstash/pipeline
          - name: logstash-data
            mountPath: /usr/share/logstash/data
          - name: logstash-logs
            mountPath: /usr/share/logstash/logs
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
      - name: logstash-data
        hostPath:
          path: /data/k8s-pv/logstash/data
      - name: logstash-logs
        hostPath:
          path: /data/k8s-pv/logstash/logs
