kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: log-app
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.9.3
          volumeMounts:
          - name: logstash-pipeline
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
