apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvs-nfs-storage
provisioner: lvs-app/nfs-client-provisioner
parameters:
  archiveOnDelete: "false"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: lvs-app
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.2.77
            - name: NFS_PATH
              value: /data/nfs/k8s-pvc
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.2.77
            path: /data/nfs/k8s-pvc
