kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lvs-nfs-test
  namespace: lvs-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lvs-nfs-storage
  resources:
    requests:
      storage: 1Mi
