kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-test
  namespace: ceph
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-storage
  resources:
    requests:
      storage: 1Mi
