apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jaeger
  namespace: istio-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvs-nfs-storage
