apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-external-tls
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - k8s-external.iisquare.com
    secretName: ingress-secret
  rules:
  - host: k8s-external.iisquare.com
    http:
      paths:
      - path: /
        backend:
          serviceName: not-exists-service
          servicePort: 80
