kind: Pod
apiVersion: v1
metadata:
  name: redis-master74
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node74
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-master75
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node75
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-master76
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node76
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-slave78
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node78
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-slave79
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node79
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
---
kind: Pod
apiVersion: v1
metadata:
  name: redis-slave80
  namespace: app-svr
  labels:
    app: redis
spec:
  nodeName: node80
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: redis
      image: redis:6.0.8
      command:
        - "redis-server"
      args:
        - "/usr/local/etc/redis/redis.conf"
        - "--protected-mode"
        - "no"
        - "--appendonly"
        - "yes"
      ports:
        - name: server
          containerPort: 6379
          hostPort: 6379
        - name: cluster
          containerPort: 16379
          hostPort: 16379
      volumeMounts:
        - name: redis-config
          mountPath: "/usr/local/etc/redis"
        - mountPath: /data
          name: redis-data
  volumes:
    - name: redis-config
      configMap:
        name: redis
        items:
          - key: "redis.conf"
            path: "redis.conf"
    - name: redis-data
      hostPath:
        path: /data/k8s-pv/redis
