apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-internal-kafka
  namespace: svr-app
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: kafka.iisquare.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kafka-manager
          servicePort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: svr-app
  labels:
    app: kafka-manager
spec:
  clusterIP: None
  selector:
    app: kafka-manager
---
kind: Pod
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: svr-app
  labels:
    app: kafka-manager
spec:
  containers:
    - name: kafka-manager
      image: kafkamanager/kafka-manager:3.0.0.4
      env:
        - name: ZK_HOSTS
          value: "192.168.2.78:2181,192.168.2.79:2181,192.168.2.80:2181/kafka"
      ports:
        - name: web
          containerPort: 9000
