kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-node78
  namespace: svr-app
  labels:
    app: kafka-node78
spec:
  selector:
    matchLabels:
      app: kafka-node78
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-node78
    spec:
      nodeName: node78
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          env:
            - name: KAFKA_BROKER_ID
              value: "78"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://192.168.2.78:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "192.168.2.78:2181,192.168.2.79:2181,192.168.2.80:2181/kafka"
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
          ports:
            - name: broker
              containerPort: 9092
              hostPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /kafka
            - name: kafka-logs
              mountPath: /opt/kafka/logs
      volumes:
        - name: kafka-data
          hostPath:
            path: /data/k8s-pv/kafka/data
        - name: kafka-logs
          hostPath:
            path: /data/k8s-pv/kafka/logs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-node79
  namespace: svr-app
  labels:
    app: kafka-node79
spec:
  selector:
    matchLabels:
      app: kafka-node79
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-node79
    spec:
      nodeName: node79
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          env:
            - name: KAFKA_BROKER_ID
              value: "79"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://192.168.2.79:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "192.168.2.78:2181,192.168.2.79:2181,192.168.2.80:2181/kafka"
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
          ports:
            - name: broker
              containerPort: 9092
              hostPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /kafka
            - name: kafka-logs
              mountPath: /opt/kafka/logs
      volumes:
        - name: kafka-data
          hostPath:
            path: /data/k8s-pv/kafka/data
        - name: kafka-logs
          hostPath:
            path: /data/k8s-pv/kafka/logs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-node80
  namespace: svr-app
  labels:
    app: kafka-node80
spec:
  selector:
    matchLabels:
      app: kafka-node80
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-node80
    spec:
      nodeName: node80
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          env:
            - name: KAFKA_BROKER_ID
              value: "80"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://192.168.2.80:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "192.168.2.78:2181,192.168.2.79:2181,192.168.2.80:2181/kafka"
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-logs
          ports:
            - name: broker
              containerPort: 9092
              hostPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /kafka
            - name: kafka-logs
              mountPath: /opt/kafka/logs
      volumes:
        - name: kafka-data
          hostPath:
            path: /data/k8s-pv/kafka/data
        - name: kafka-logs
          hostPath:
            path: /data/k8s-pv/kafka/logs
