apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-harbor
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-harbor
  nfs:
    path: /data/nfs/harbor
    server: 192.168.2.77
