kind: Pod
apiVersion: v1
metadata:
  name: mongo-node78
  namespace: app-svr
  labels:
    app: mongo
spec:
  nodeName: node78
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: mongo
      image: mongo:4.4.6
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin888
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--bind_ip"
        - "192.168.2.78"
        - "--auth"
        - "--keyFile"
        - "/etc/mongodb-keyfile"
      ports:
        - name: server
          containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: "/etc/mongodb-keyfile"
          subPath: mongodb-keyfile
  volumes:
    - name: mongo-data
      hostPath:
        path: /data/k8s-pv/mongo/data
    - name: mongo-config
      configMap:
        name: mongo
        defaultMode: 0600
---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-node79
  namespace: app-svr
  labels:
    app: mongo
spec:
  nodeName: node79
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: mongo
      image: mongo:4.4.6
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin888
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--bind_ip"
        - "192.168.2.79"
        - "--auth"
        - "--keyFile"
        - "/etc/mongodb-keyfile"
      ports:
        - name: server
          containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: "/etc/mongodb-keyfile"
          subPath: mongodb-keyfile
  volumes:
    - name: mongo-data
      hostPath:
        path: /data/k8s-pv/mongo/data
    - name: mongo-config
      configMap:
        name: mongo
        defaultMode: 0600
---
kind: Pod
apiVersion: v1
metadata:
  name: mongo-node80
  namespace: app-svr
  labels:
    app: mongo
spec:
  nodeName: node80
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  containers:
    - name: mongo
      image: mongo:4.4.6
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin888
      command:
        - mongod
        - "--replSet"
        - rs0
        - "--bind_ip"
        - "192.168.2.80"
        - "--auth"
        - "--keyFile"
        - "/etc/mongodb-keyfile"
      ports:
        - name: server
          containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-config
          mountPath: "/etc/mongodb-keyfile"
          subPath: mongodb-keyfile
  volumes:
    - name: mongo-data
      hostPath:
        path: /data/k8s-pv/mongo/data
    - name: mongo-config
      configMap:
        name: mongo
        defaultMode: 0600
---
